export const ballsData = [
  {
    className:"icon_star_guangzhou",
    x:"121",
    y:"-3",
    width:"112",
    height:"112",
    xlinkHref:require("@/assets/images/center/star.png")
  },
  {
    className:"icon_location_zhongshan",
    x:"666",
    y:"287",
    width:"106",
    height:"107",
    xlinkHref:require("@/assets/images/center/location.png")
  },
  {
    className:"icon_pie_shenzhen",
    x:"13",
    y:"194",
    width:"107",
    height:"108",
    xlinkHref:require("@/assets/images/center/pie.png")
  },
  {
    className:"icon_earth_dongguan",
    x:"106",
    y:"460",
    width:"111",
    height:"112",
    xlinkHref:require("@/assets/images/center/earth.png")
  },
  {
    className:"icon_hot_zhuhai",
    x:"530",
    y:"495",
    width:"105",
    height:"105",
    xlinkHref:require("@/assets/images/center/hot.png")
  }
]